server:
  port: 8081  # <--- Su propio puerto para no chocar con nadie

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

# La misma estructura que usamos en Inventario
jwt:
  secret: 841D8A6C80CBA4FAA6E14BF7F2A21430F87208FCA46D2967F550269BE6B19B00FBE8B51E2833FDE4384D6F39F931D3156291C7C9E7D8A7490A5BE0A272A5EE
  expiration: 86400000